# Generated by Django 5.1.1 on 2024-12-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0002_orderitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatusinfo',
            options={},
        ),
    ]
