# Generated by Django 5.1.1 on 2024-12-26 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0003_alter_orderstatusinfo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderstatusinfo',
            name='is_delivery_payment',
            field=models.BooleanField(default=False, verbose_name='Оплачена ли доставка в РФ'),
        ),
        migrations.AddField(
            model_name='orderstatusinfo',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ori', to='legacy.orders'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderstatusinfo',
            name='order_currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orderstatusinfo',
            name='order_sum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='orderstatusinfo',
            name='buyer',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='Покупатель'),
        ),
        migrations.AlterField(
            model_name='orderstatusinfo',
            name='host_country',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна назначения'),
        ),
        migrations.AlterField(
            model_name='orderstatusinfo',
            name='payment_card',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Карта для оплаты'),
        ),
        migrations.AlterField(
            model_name='orderstatusinfo',
            name='post_service',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Почтовая служба'),
        ),
        migrations.AlterField(
            model_name='orderstatusinfo',
            name='success',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата получения посылки'),
        ),
    ]
