# Generated by Django 5.1.1 on 2025-01-02 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0004_orderstatusinfo_is_delivery_payment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderstatusinfo',
            options={'managed': False},
        ),
    ]
