# Generated by Django 5.1.1 on 2025-04-07 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Артикул для поиска')),
                ('title', models.CharField(max_length=255, verbose_name='Название статьи')),
                ('photo_title', models.CharField(max_length=255, verbose_name='Название фото статьи')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='articles', verbose_name='Фото статьи')),
                ('meta_title', models.CharField(max_length=255, verbose_name='Мета заголовок')),
                ('content', models.TextField(verbose_name='Содержимое статьи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
            },
        ),
    ]
