# Generated by Django 5.1.1 on 2025-04-10 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_alter_article_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='photo',
        ),
        migrations.AlterField(
            model_name='article',
            name='photo_title',
            field=models.CharField(max_length=255, verbose_name='Фото плитки в статье'),
        ),
    ]
