# Generated by Django 5.1.1 on 2025-04-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0003_remove_article_photo_alter_article_photo_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pre_view',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Тизер статьи'),
        ),
    ]
