# cat app_front/migrations/0001_initial.py
# Generated by Django 5.1.1 on 2024-10-28 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallbackForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('connect', models.CharField(blank=True, max_length=100, null=True, verbose_name='Предпочтительный способ связи')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('message', models.TextField(max_length=4000, verbose_name='Что случилось?')),
            ],
        ),
    ]
