# Generated by Django 5.1.1 on 2025-01-03 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_alter_groupinfo_options_alter_groupinfo_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupinfo',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
