# Generated by Django 5.1.1 on 2025-01-03 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_groupinfo_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupinfo',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
