# Generated by Django 5.1.1 on 2025-01-04 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0005_alter_orderstatusinfo_options'),
        ('panel', '0007_alter_groupinfo_order_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordersgroup',
            options={'verbose_name': 'Info', 'verbose_name_plural': 'Row Info'},
        ),
        migrations.AddField(
            model_name='ordersgroup',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='row_buyer', to='legacy.buyers'),
        ),
        migrations.AddField(
            model_name='ordersgroup',
            name='buyer_reward',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordersgroup',
            name='comment',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordersgroup',
            name='estimated_date_of_arrival',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ориентировочная дата прибытия КЗ'),
        ),
        migrations.AddField(
            model_name='ordersgroup',
            name='forward_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordersgroup',
            name='is_delivery_payment',
            field=models.BooleanField(default=False, verbose_name='Оплачена ли доставка в РФ'),
        ),
        migrations.AddField(
            model_name='ordersgroup',
            name='is_forward',
            field=models.BooleanField(default=False, verbose_name='Заказ через форвардера'),
        ),
        migrations.AddField(
            model_name='ordersgroup',
            name='order_currency',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordersgroup',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordersgroup',
            name='order_sum',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordersgroup',
            name='payment_card',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Карта для оплаты'),
        ),
        migrations.AddField(
            model_name='ordersgroup',
            name='post_service',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Почтовая служба'),
        ),
        migrations.AddField(
            model_name='ordersgroup',
            name='shop',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordersgroup',
            name='store_order_number',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordersgroup',
            name='trek',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='GroupInfo',
        ),
    ]
