# Generated by Django 5.1.1 on 2025-03-25 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legacy', '0006_alter_orderstatus_options_and_more'),
        ('panel', '0008_alter_ordersgroup_options_ordersgroup_buyer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordersgroup',
            options={'verbose_name': 'Информация о заказах', 'verbose_name_plural': 'Информация о заказах'},
        ),
        migrations.AlterField(
            model_name='ordersgroup',
            name='buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='row_buyer', to='legacy.buyers', verbose_name='Байер'),
        ),
        migrations.AlterField(
            model_name='ordersgroup',
            name='buyer_reward',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Вознаграждение баера'),
        ),
        migrations.AlterField(
            model_name='ordersgroup',
            name='forward_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Форвардер название'),
        ),
        migrations.AlterField(
            model_name='ordersgroup',
            name='is_forward',
            field=models.BooleanField(default=False, verbose_name='True если заказ через форвардера'),
        ),
        migrations.AlterField(
            model_name='ordersgroup',
            name='order_currency',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='ordersgroup',
            name='order_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата заказа'),
        ),
        migrations.AlterField(
            model_name='ordersgroup',
            name='order_sum',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Сумма заказа'),
        ),
        migrations.AlterField(
            model_name='ordersgroup',
            name='shop',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Магазин'),
        ),
        migrations.AlterField(
            model_name='ordersgroup',
            name='store_order_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер заказа в магазине/номер заказа у Форвардера'),
        ),
        migrations.AlterField(
            model_name='ordersgroup',
            name='trek',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Трек'),
        ),
    ]
