# Generated by Django 5.1.1 on 2025-03-25 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Название в базе')),
                ('name_rus', models.CharField(max_length=255, unique=True, verbose_name='Название на сайте')),
                ('image', models.ImageField(upload_to='shop_categories')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='shop_links')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('link_address', models.URLField()),
                ('link_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Битая ссылка или нет')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_shops', to='seo.shopcategory')),
            ],
        ),
    ]
