# Generated by Django 5.1.1 on 2025-03-25 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0002_alter_shopitem_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopcategory',
            options={'verbose_name': 'Категория магазина', 'verbose_name_plural': 'Категории магазинов'},
        ),
        migrations.AlterModelOptions(
            name='shopitem',
            options={'verbose_name': 'Ссылка на мазазин', 'verbose_name_plural': 'Ссылки на магазины'},
        ),
        migrations.AddField(
            model_name='shopitem',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='Ссылка в пре релизе или нет'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Сервисы'),
        ),
    ]
