# Generated by Django 5.1.1 on 2025-03-25 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_alter_shopcategory_options_alter_shopitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopitem',
            options={'verbose_name': 'Ссылка на магазин', 'verbose_name_plural': 'Ссылки на магазины'},
        ),
    ]
