# Generated by Django 5.1.1 on 2025-03-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0004_alter_shopitem_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopcategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shopcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='shop_categories'),
        ),
    ]
