# Generated by Django 5.1.1 on 2025-03-25 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0005_alter_shopcategory_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop_items', to='seo.shopcategory'),
        ),
    ]
