# Generated by Django 5.1.1 on 2025-03-25 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0006_alter_shopitem_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Название магазина'),
        ),
    ]
