# Generated by Django 5.1.1 on 2025-03-27 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0007_alter_shopitem_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopcategory',
            name='priority',
            field=models.IntegerField(default=10, verbose_name='Приоритет'),
        ),
    ]
