# Generated by Django 5.1.1 on 2025-03-27 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0008_shopcategory_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='shop_items', to='seo.shopcategory'),
        ),
    ]
